name: Unit Test

on:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Vite Plus
        uses: bjmhe/workflows/setup-vp@vp
        with:
          node-version: 24

      - name: Install @mermaid-js/mermaid-cli
        run: vp install @mermaid-js/mermaid-cli -g

      - name: Install Puppeteer
        run: PUPPETEER_SKIP_DOWNLOAD=true vp install puppeteer -g

      - name: Install Chrome
        run: puppeteer browsers install chrome-headless-shell

      - name: Build
        run: vp run build

      - name: Test
        run: vp test
