name: Unit Test

on:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Vite Plus
        uses: bjmhe/workflows/setup-vp@vp
        with:
          node-version: 24
          auto-install: false
      - name: Clean Puppeteer Cache
        run: rm -rf ~/.cache/puppeteer/chrome-headless-shell

      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true vp install

      - name: Install Puppeteer
        run: npx puppeteer browsers install chrome-headless-shell

      - name: Build
        run: vp run build

      - name: Test
        run: vp test
